const AUGMENT_VERSION='3.1';
const AUGMENT_SETTINGS_KEY='nexal-v3-settings';
const PUTER_HISTORY_KEY='nexal-v3-puter-history';
const cloudModels=[
  {id:'openai/gpt-5.4-nano',label:'GPT-5.4 Nano',note:'Fast cloud fallback'},
  {id:'anthropic/claude-sonnet-5',label:'Claude Sonnet 5',note:'Coding & writing'},
  {id:'google/gemini-3.1-pro-preview',label:'Gemini 3.1 Pro',note:'Deep reasoning'},
  {id:'openai/gpt-5.4',label:'GPT-5.4',note:'Frontier general model'}
];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function savedSettings(){try{return JSON.parse(localStorage.getItem(AUGMENT_SETTINGS_KEY)||'{}')}catch{return{}}}
function toast(message,bad=false){let stack=document.querySelector('.toast-stack');if(!stack){stack=document.createElement('div');stack.className='toast-stack';document.body.append(stack)}const t=document.createElement('div');t.className='toast'+(bad?' bad':'');t.textContent=message;stack.append(t);setTimeout(()=>t.remove(),4200)}
function addStyles(){const s=document.createElement('style');s.textContent=`
.nx-cloud-btn{height:34px;padding:0 11px;border:1px solid var(--line);border-radius:999px;background:var(--panel);color:#dce2ed;cursor:pointer;font:inherit;font-size:12px;display:inline-flex;align-items:center;gap:7px}.nx-cloud-btn:hover{background:var(--panel2);border-color:var(--line2)}
.nx-modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(5px);z-index:110;display:grid;place-items:center;padding:18px}.nx-modal{width:min(820px,100%);max-height:min(760px,90vh);background:#11151d;border:1px solid var(--line2);border-radius:18px;box-shadow:var(--shadow);display:grid;grid-template-rows:auto minmax(0,1fr) auto;overflow:hidden}.nx-modal-head{height:58px;padding:0 16px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:10px}.nx-modal-head strong{font-size:14px}.nx-modal-head small{color:var(--muted)}.nx-modal-head button{margin-left:auto}.nx-cloud-body{min-height:0;overflow:auto;padding:16px;display:grid;gap:12px}.nx-cloud-note{padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:#0e1218;color:var(--muted);font-size:12px;line-height:1.5}.nx-cloud-controls{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.nx-cloud-controls select,.nx-cloud-compose textarea{width:100%;border:1px solid var(--line);background:#0f131a;color:var(--text);border-radius:11px;padding:10px;outline:none}.nx-cloud-compose{padding:12px 16px 16px;border-top:1px solid var(--line)}.nx-cloud-compose textarea{min-height:90px;resize:vertical}.nx-cloud-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:8px}.nx-cloud-output{white-space:pre-wrap;line-height:1.6;background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:13px;min-height:90px}.nx-cloud-meta{font-size:10px;color:var(--faint);margin-top:6px}.nx-search-tool{border-color:#3b4864!important;color:#d8e1ff!important}.nx-search-mark{font-size:9px;border:1px solid #536a9d;border-radius:999px;padding:2px 5px;color:#b9caff}.nx-use-btn{margin-top:8px}.nx-spinner{display:inline-block;width:13px;height:13px;border:2px solid #596274;border-top-color:#fff;border-radius:50%;animation:nxspin .7s linear infinite}@keyframes nxspin{to{transform:rotate(360deg)}}
@media(max-width:720px){.nx-cloud-btn span:last-child{display:none}.nx-cloud-controls{grid-template-columns:1fr}.nx-modal{max-height:92vh}}
`;document.head.append(s)}
function coreContext(){return [...document.querySelectorAll('.message')].slice(-10).map(node=>{const role=node.classList.contains('user')?'User':'Assistant';const text=node.querySelector('.message-body')?.innerText?.trim();return text?`${role}: ${text}`:''}).filter(Boolean).join('\n\n').slice(0,12000)}
function insertIntoComposer(text){const ta=document.querySelector('#composerInput');if(!ta){toast('Open a chat first',true);return}ta.value=text;ta.dispatchEvent(new Event('input',{bubbles:true}));ta.focus();ta.scrollIntoView({block:'center',behavior:'smooth'})}
async function webSearch(){const query=prompt('Search the web for:');if(!query)return;toast('Searching the web…');const settings=savedSettings();const headers={Accept:'text/plain'};if(settings.jinaKey)headers.Authorization=`Bearer ${settings.jinaKey}`;try{const r=await fetch('https://s.jina.ai/'+encodeURIComponent(query),{headers});if(!r.ok){if(r.status===401)throw new Error('Jina Search needs a free Jina key. Add it in Nexal AI Settings.');throw new Error(`Search returned ${r.status}`)}const text=(await r.text()).slice(0,10000);insertIntoComposer(`Use these live web-search results as grounding for my question. Prefer the supplied sources when relevant and tell me when they are insufficient.\n\n### Web search: ${query}\n${text}\n\n### My question\n${query}`);toast('Live search results added to the composer')}catch(e){toast(e.message,true)}}
function addSearchTool(){const left=document.querySelector('.composer-left');if(!left||left.querySelector('[data-nx-search]'))return;const b=document.createElement('button');b.className='composer-tool nx-search-tool';b.dataset.nxSearch='1';b.innerHTML='<span class="nx-search-mark">LIVE</span><span>Search</span>';b.onclick=webSearch;left.append(b)}
async function ensurePuter(){if(window.puter?.ai)return window.puter;if(document.querySelector('script[data-nx-puter]')){for(let i=0;i<80;i++){if(window.puter?.ai)return window.puter;await sleep(100)}throw new Error('Puter.js did not initialize')}return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://js.puter.com/v2/';s.async=true;s.dataset.nxPuter='1';s.onload=()=>window.puter?.ai?resolve(window.puter):reject(new Error('Puter AI unavailable'));s.onerror=()=>reject(new Error('Could not load Puter.js'));document.head.append(s)})}
function responseText(response){if(typeof response==='string')return response;const c=response?.message?.content??response?.text??response?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map(x=>x?.text||x?.content||'').join('\n').trim();return JSON.stringify(response,null,2)}
function cloudHistory(){try{return JSON.parse(localStorage.getItem(PUTER_HISTORY_KEY)||'[]')}catch{return[]}}
function saveCloudHistory(items){localStorage.setItem(PUTER_HISTORY_KEY,JSON.stringify(items.slice(-20)))}
function closeCloud(){document.querySelector('.nx-modal-backdrop')?.remove()}
function openCloud(){closeCloud();const back=document.createElement('div');back.className='nx-modal-backdrop';back.onclick=e=>{if(e.target===back)closeCloud()};const modal=document.createElement('section');modal.className='nx-modal';const head=document.createElement('div');head.className='nx-modal-head';head.innerHTML='<strong>Cloud Models</strong><small>Optional high-intelligence fallback</small><button class="icon-btn" aria-label="Close">×</button>';head.querySelector('button').onclick=closeCloud;const body=document.createElement('div');body.className='nx-cloud-body';body.innerHTML='<div class="nx-cloud-note"><strong>Why this exists:</strong> AI Horde stays the default low-refusal R0 engine. This optional panel uses Puter.js when you want GPT, Claude or Gemini. Puter requires no developer API key; each user gets a free allowance and their own Puter account covers usage beyond it.</div>';const controls=document.createElement('div');controls.className='nx-cloud-controls';const select=document.createElement('select');for(const m of cloudModels){const o=document.createElement('option');o.value=m.id;o.textContent=`${m.label} — ${m.note}`;select.append(o)}const clear=document.createElement('button');clear.className='ghost-btn';clear.textContent='Clear history';clear.onclick=()=>{saveCloudHistory([]);renderHistory()};controls.append(select,clear);const history=document.createElement('div');history.id='nxCloudHistory';body.append(controls,history);const compose=document.createElement('div');compose.className='nx-cloud-compose';const ta=document.createElement('textarea');ta.placeholder='Ask a cloud model…';const actions=document.createElement('div');actions.className='nx-cloud-actions';const useContext=document.createElement('label');useContext.style.cssText='margin-right:auto;color:var(--muted);font-size:11px;display:flex;gap:6px;align-items:center';useContext.innerHTML='<input type="checkbox" checked> Include current Nexal chat';const send=document.createElement('button');send.className='primary-btn';send.textContent='Ask model';actions.append(useContext,send);compose.append(ta,actions);modal.append(head,body,compose);back.append(modal);document.body.append(back);
function renderHistory(){history.innerHTML='';const items=cloudHistory();if(!items.length){const empty=document.createElement('div');empty.className='nx-cloud-output';empty.style.color='var(--muted)';empty.textContent='Cloud-model answers will appear here.';history.append(empty);return}for(const item of items.slice().reverse()){const wrap=document.createElement('div');wrap.style.marginBottom='10px';const out=document.createElement('div');out.className='nx-cloud-output';out.textContent=item.answer;const meta=document.createElement('div');meta.className='nx-cloud-meta';meta.textContent=`${item.model} · ${new Date(item.time).toLocaleString()}`;const use=document.createElement('button');use.className='ghost-btn nx-use-btn';use.textContent='Use as Nexal chat context';use.onclick=()=>{insertIntoComposer(`A cloud model produced the following analysis. Treat it as supporting context, verify it when needed, and answer my next request using the strongest parts:\n\n${item.answer}\n\nMy next request: `);closeCloud()};wrap.append(out,meta,use);history.append(wrap)}}renderHistory();
send.onclick=async()=>{const promptText=ta.value.trim();if(!promptText)return;send.disabled=true;send.innerHTML='<span class="nx-spinner"></span> Working';try{const p=await ensurePuter();const context=useContext.querySelector('input').checked?coreContext():'';const full=context?`Current Nexal conversation for context:\n${context}\n\nUser request:\n${promptText}`:promptText;const response=await p.ai.chat(full,{model:select.value});const answer=responseText(response);const items=cloudHistory();items.push({model:select.value,prompt:promptText,answer,time:Date.now()});saveCloudHistory(items);ta.value='';renderHistory();toast('Cloud-model answer ready')}catch(e){toast(e.message||'Cloud request failed',true)}finally{send.disabled=false;send.textContent='Ask model'}};ta.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')send.click()}}
function addCloudButton(){const bar=document.querySelector('.topbar');if(!bar||bar.querySelector('[data-nx-cloud]'))return;const spacer=bar.querySelector('.topbar-spacer');const b=document.createElement('button');b.className='nx-cloud-btn';b.dataset.nxCloud='1';b.innerHTML='<span>✦</span><span>Cloud Models</span>';b.onclick=openCloud;if(spacer)spacer.after(b);else bar.append(b)}
function upgradePluginPage(){const host=document.querySelector('.panel-view');if(!host||host.querySelector('[data-nx-augment]'))return;if(!document.body.textContent.includes('Abilities & plugins'))return;const card=document.createElement('div');card.className='card';card.dataset.nxAugment='1';card.style.marginTop='12px';card.innerHTML='<h3>v3.1 cloud & research layer</h3><p>Added live Jina web search and optional Puter cloud-model access. Horde remains the default engine; cloud models are a deliberate fallback for higher-end reasoning, coding and synthesis.</p><div class="plugin-meta"><span class="tag">Jina Search</span><span class="tag">Puter.js</span><span class="tag">GPT</span><span class="tag">Claude</span><span class="tag">Gemini</span></div>';host.append(card)}
function enhance(){addCloudButton();addSearchTool();upgradePluginPage()}
addStyles();enhance();const observer=new MutationObserver(()=>enhance());observer.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('beforeunload',()=>observer.disconnect());
