let nxToolsMenu=null,nxPolishBusy=false;
function nxPolishStyles(){if(document.querySelector('#nx-polish-style'))return;const s=document.createElement('style');s.id='nx-polish-style';s.textContent=`
.topbar-title{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.nx-tools-dock{display:flex;align-items:center;gap:6px}.nx-tools-items{display:flex;align-items:center;gap:6px}.nx-tools-menu-btn{display:none;height:34px;padding:0 10px;border:1px solid var(--line);border-radius:999px;background:var(--panel);color:#dce3ee;cursor:pointer;font:inherit;font-size:12px;align-items:center;gap:6px}.nx-tools-popover{position:fixed;z-index:145;width:min(280px,calc(100vw - 24px));padding:7px;background:#11151d;border:1px solid var(--line2);border-radius:14px;box-shadow:var(--shadow);display:grid;gap:4px}.nx-tools-popover button{width:100%;display:flex;align-items:center;gap:9px;text-align:left;border:0;background:transparent;color:var(--text);border-radius:9px;padding:10px 11px;cursor:pointer;font:inherit;font-size:12px}.nx-tools-popover button:hover{background:var(--panel2)}.nx-tools-popover small{margin-left:auto;color:var(--faint);font-size:9px}.nx-reserved{display:inline-flex;margin-top:7px;padding:3px 7px;border:1px solid #50596b;border-radius:999px;color:#9ea8b7;font-size:9px;text-transform:uppercase;letter-spacing:.08em}.plugin-card .switch:disabled{cursor:not-allowed;opacity:.45}.nx-focus-ring :focus-visible{outline:2px solid #8ba4ff!important;outline-offset:2px!important}.sidebar.open{box-shadow:0 28px 70px rgba(0,0,0,.52)}
@media(max-width:1050px){.topbar{gap:7px}.nx-tools-items>button{padding-left:8px;padding-right:8px}.nx-tools-items>button span:last-child{display:none}}
@media(max-width:820px){.nx-tools-items{display:none}.nx-tools-menu-btn{display:inline-flex}.topbar .ghost-btn{padding-left:8px;padding-right:8px}.topbar .kbd{display:none}.route-pill .route-name{max-width:90px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
@media(max-width:560px){.topbar-title{max-width:26vw}.r0-badge{display:none}.route-pill{padding:0 8px}.route-pill .route-name{display:none}.topbar>.ghost-btn{font-size:0}.topbar>.ghost-btn svg{margin:0}}
`;document.head.append(s);document.documentElement.classList.add('nx-focus-ring')}
function nxToolSources(){return[['[data-nx-cloud]','Cloud Models','✦'],['[data-nx-workspace]','Workspace','◇'],['[data-nx-python]','Python Lab','⌘'],['[data-nx-repo]','Repo Inspector','⌗']].map(([sel,label,glyph])=>({el:document.querySelector(sel),label,glyph})).filter(x=>x.el)}
function nxCloseTools(){nxToolsMenu?.remove();nxToolsMenu=null}
function nxOpenTools(button){nxCloseTools();const menu=document.createElement('div');menu.className='nx-tools-popover';for(const item of nxToolSources()){const b=document.createElement('button');b.innerHTML=`<span>${item.glyph}</span><span>${item.label}</span><small>Open</small>`;b.onclick=()=>{nxCloseTools();item.el.click()};menu.append(b)}document.body.append(menu);const r=button.getBoundingClientRect(),w=Math.min(280,innerWidth-24);menu.style.left=Math.max(12,Math.min(innerWidth-w-12,r.right-w))+'px';menu.style.top=Math.min(innerHeight-menu.offsetHeight-12,r.bottom+8)+'px';nxToolsMenu=menu}
function nxBuildDock(){if(nxPolishBusy)return;nxPolishBusy=true;try{const bar=document.querySelector('.topbar');if(!bar)return;let dock=bar.querySelector('.nx-tools-dock');if(!dock){dock=document.createElement('div');dock.className='nx-tools-dock';const items=document.createElement('div');items.className='nx-tools-items';const menu=document.createElement('button');menu.className='nx-tools-menu-btn';menu.dataset.nxToolsMenu='1';menu.innerHTML='<span>⋯</span><span>Tools</span>';menu.onclick=()=>nxOpenTools(menu);dock.append(items,menu);const spacer=bar.querySelector('.topbar-spacer');if(spacer)spacer.after(dock);else bar.append(dock)}const items=dock.querySelector('.nx-tools-items');for(const source of nxToolSources())if(source.el.parentElement!==items)items.append(source.el)}finally{nxPolishBusy=false}}
function nxMarkReserved(){for(const card of document.querySelectorAll('.plugin-card')){if(!/OpenAI-Compatible Endpoint/i.test(card.textContent||''))continue;if(card.dataset.nxReserved)return;card.dataset.nxReserved='1';const sw=card.querySelector('.switch');if(sw){sw.disabled=true;sw.classList.remove('on');sw.title='Reserved extension boundary — not connected yet'}const main=card.querySelector('.plugin-main')||card;if(!main.querySelector('.nx-reserved')){const badge=document.createElement('span');badge.className='nx-reserved';badge.textContent='Reserved · not active';main.append(badge)}}}
function nxMobileSidebarGuard(){const side=document.querySelector('#sidebar');if(!side)return;document.addEventListener('click',e=>{if(innerWidth>820||!side.classList.contains('open'))return;if(side.contains(e.target)||e.target.closest('.mobile-menu'))return;side.classList.remove('open')},{passive:true})}
function nxEnhance(){nxBuildDock();nxMarkReserved()}
nxPolishStyles();nxEnhance();nxMobileSidebarGuard();const nxPolishObserver=new MutationObserver(nxEnhance);nxPolishObserver.observe(document.documentElement,{subtree:true,childList:true});document.addEventListener('click',e=>{if(nxToolsMenu&&!nxToolsMenu.contains(e.target)&&!e.target.closest('[data-nx-tools-menu]'))nxCloseTools()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nxCloseTools();document.querySelector('#sidebar')?.classList.remove('open')}});window.addEventListener('resize',nxCloseTools,{passive:true});window.addEventListener('beforeunload',()=>nxPolishObserver.disconnect());
