const NX_KEYS={settings:'nexal-v3-settings',conversations:'nexal-v3-conversations',plugins:'nexal-v3-plugins',active:'nexal-v3-active',cloud:'nexal-v3-puter-history'};
const NX_PRESETS=[
  {name:'Direct',desc:'Short, decisive everyday answers',prompt:'Be useful, accurate and direct. Give the final answer without narrating hidden reasoning. Follow explicit formatting instructions exactly. Clearly distinguish facts from uncertainty.'},
  {name:'Researcher',desc:'Evidence-first research and synthesis',prompt:'Act as a rigorous research assistant. Separate verified facts, reasonable inference, and uncertainty. Use supplied sources and context carefully, compare conflicting evidence, and end with the clearest supported conclusion. Do not narrate hidden reasoning.'},
  {name:'Builder',desc:'Coding, debugging and implementation',prompt:'Act as a senior software builder. Prefer concrete implementation over theory. Inspect constraints, identify likely failure modes, produce minimal robust code or steps, and verify assumptions. Do not narrate hidden reasoning.'},
  {name:'Business',desc:'Revenue, strategy and execution',prompt:'Act as a practical business operator. Prioritize actions by expected value, speed, cost, and risk. Challenge weak assumptions, quantify when possible, and finish with the next executable move. Do not narrate hidden reasoning.'},
  {name:'Writer',desc:'Natural polished writing',prompt:'Write naturally, clearly, and specifically. Match the requested audience and tone, avoid repetitive AI-style phrasing, and preserve the user’s intended meaning. Return only the useful finished output unless explanation is requested.'}
];
const q=s=>document.querySelector(s);
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function nxToast(message,bad=false){let stack=q('.toast-stack');if(!stack){stack=document.createElement('div');stack.className='toast-stack';document.body.append(stack)}const t=document.createElement('div');t.className='toast'+(bad?' bad':'');t.textContent=message;stack.append(t);setTimeout(()=>t.remove(),3800)}
function nxActive(){return localStorage.getItem(NX_KEYS.active)||''}
function nxConversations(){return read(NX_KEYS.conversations,[])}
function nxCurrent(){const id=nxActive();return nxConversations().find(c=>c.id===id)}
function nxReload(){location.reload()}
function nxRename(){const list=nxConversations(),id=nxActive(),c=list.find(x=>x.id===id);if(!c)return nxToast('No active conversation',true);const name=prompt('Rename conversation:',c.title||'New conversation');if(!name?.trim())return;c.title=name.trim().slice(0,80);c.updated=Date.now();write(NX_KEYS.conversations,list);nxToast('Conversation renamed');setTimeout(nxReload,250)}
function nxDuplicate(){const list=nxConversations(),id=nxActive(),c=list.find(x=>x.id===id);if(!c)return nxToast('No active conversation',true);const copy=structuredClone(c);copy.id=crypto.randomUUID?.()||String(Date.now()+Math.random());copy.title=(c.title||'Conversation')+' copy';copy.created=Date.now();copy.updated=Date.now();list.unshift(copy);write(NX_KEYS.conversations,list);localStorage.setItem(NX_KEYS.active,copy.id);nxToast('Conversation duplicated');setTimeout(nxReload,250)}
function nxExport(){const payload={version:'3.2',exportedAt:new Date().toISOString(),settings:{...read(NX_KEYS.settings,{}),hordeKey:'',jinaKey:''},plugins:read(NX_KEYS.plugins,{}),conversations:nxConversations(),activeId:nxActive()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexal-ai-workspace-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);nxToast('Workspace exported without API keys')}
function nxImport(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.conversations))throw new Error('This file does not contain a Nexal conversation list.');if(!data.conversations.every(c=>c&&typeof c.id==='string'&&Array.isArray(c.messages)))throw new Error('Conversation data is malformed.');const replace=confirm(`Import ${data.conversations.length} conversations?\n\nOK = replace this browser workspace\nCancel = merge them with the current workspace`);let next;if(replace){next=data.conversations}else{const current=nxConversations(),ids=new Set(current.map(c=>c.id));next=[...data.conversations.map(c=>ids.has(c.id)?{...c,id:crypto.randomUUID?.()||String(Date.now()+Math.random())}:c),...current]}write(NX_KEYS.conversations,next);if(data.settings&&typeof data.settings==='object'){const current=read(NX_KEYS.settings,{});write(NX_KEYS.settings,{...current,...data.settings,hordeKey:current.hordeKey||'',jinaKey:current.jinaKey||''})}if(data.plugins&&typeof data.plugins==='object')write(NX_KEYS.plugins,{...read(NX_KEYS.plugins,{}),...data.plugins});localStorage.setItem(NX_KEYS.active,next[0]?.id||'');nxToast(replace?'Workspace restored':'Workspace merged');setTimeout(nxReload,350)}catch(e){nxToast('Import failed: '+e.message,true)}};input.click()}
function nxApplyPreset(preset){const settings=read(NX_KEYS.settings,{});settings.systemPrompt=preset.prompt;write(NX_KEYS.settings,settings);nxToast(`${preset.name} skill activated`)}
function nxClearCloud(){if(confirm('Clear locally stored Cloud Models history?')){localStorage.removeItem(NX_KEYS.cloud);nxToast('Cloud history cleared')}}
function nxStats(){const conv=nxConversations(),messages=conv.reduce((n,c)=>n+(c.messages?.length||0),0),chars=conv.reduce((n,c)=>n+(c.messages||[]).reduce((m,x)=>m+String(x.content||'').length,0),0);return{conversations:conv.length,messages,chars}}
function closeNxWorkspace(){q('.nx-workspace-backdrop')?.remove()}
function openNxWorkspace(){closeNxWorkspace();const stats=nxStats(),back=document.createElement('div');back.className='nx-workspace-backdrop';back.onclick=e=>{if(e.target===back)closeNxWorkspace()};const modal=document.createElement('section');modal.className='nx-workspace-modal';modal.innerHTML=`<div class="nx-workspace-head"><div><strong>Workspace</strong><small>Local data, conversation tools & skills</small></div><button class="icon-btn" data-close>×</button></div><div class="nx-workspace-body"><div class="nx-stat-grid"><div><strong>${stats.conversations}</strong><span>Conversations</span></div><div><strong>${stats.messages}</strong><span>Messages</span></div><div><strong>${Math.round(stats.chars/1000)}k</strong><span>Local chars</span></div></div><div class="nx-workspace-section"><h3>Current conversation</h3><div class="nx-workspace-actions"><button data-rename>Rename</button><button data-duplicate>Duplicate</button></div></div><div class="nx-workspace-section"><h3>Portable workspace</h3><p>Export strips API keys. Import can replace or merge with this browser.</p><div class="nx-workspace-actions"><button data-export>Export</button><button data-import>Import</button></div></div><div class="nx-workspace-section"><h3>Skills</h3><p>Skills change the core system instruction locally. Switch whenever the job changes.</p><div class="nx-preset-grid"></div></div><div class="nx-workspace-section"><h3>Maintenance</h3><div class="nx-workspace-actions"><button data-clear-cloud>Clear Cloud Models history</button></div></div></div>`;modal.querySelector('[data-close]').onclick=closeNxWorkspace;modal.querySelector('[data-rename]').onclick=nxRename;modal.querySelector('[data-duplicate]').onclick=nxDuplicate;modal.querySelector('[data-export]').onclick=nxExport;modal.querySelector('[data-import]').onclick=nxImport;modal.querySelector('[data-clear-cloud]').onclick=nxClearCloud;const grid=modal.querySelector('.nx-preset-grid');for(const p of NX_PRESETS){const b=document.createElement('button');b.innerHTML=`<strong>${p.name}</strong><span>${p.desc}</span>`;b.onclick=()=>nxApplyPreset(p);grid.append(b)}back.append(modal);document.body.append(back)}
function nxStyles(){if(q('#nx-workspace-style'))return;const s=document.createElement('style');s.id='nx-workspace-style';s.textContent=`.nx-workspace-btn{height:34px;padding:0 10px;border:1px solid var(--line);border-radius:999px;background:var(--panel);color:#d8dee8;cursor:pointer;font:inherit;font-size:12px}.nx-workspace-btn:hover{background:var(--panel2)}.nx-workspace-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(5px);z-index:115;display:grid;place-items:center;padding:18px}.nx-workspace-modal{width:min(720px,100%);max-height:90vh;overflow:hidden;background:#11151d;border:1px solid var(--line2);border-radius:18px;box-shadow:var(--shadow);display:grid;grid-template-rows:auto minmax(0,1fr)}.nx-workspace-head{height:62px;border-bottom:1px solid var(--line);padding:0 16px;display:flex;align-items:center}.nx-workspace-head>div{display:grid;gap:2px}.nx-workspace-head strong{font-size:14px}.nx-workspace-head small{color:var(--muted);font-size:11px}.nx-workspace-head button{margin-left:auto}.nx-workspace-body{overflow:auto;padding:15px}.nx-stat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.nx-stat-grid>div{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px;display:grid;gap:3px}.nx-stat-grid strong{font-size:19px}.nx-stat-grid span{font-size:10px;color:var(--muted)}.nx-workspace-section{margin-top:12px;padding:13px;border:1px solid var(--line);border-radius:13px;background:#0f131a}.nx-workspace-section h3{font-size:13px;margin:0 0 5px}.nx-workspace-section p{font-size:11px;color:var(--muted);margin:0 0 9px;line-height:1.5}.nx-workspace-actions{display:flex;gap:7px;flex-wrap:wrap}.nx-workspace-actions button,.nx-preset-grid button{border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:9px;padding:8px 10px;cursor:pointer}.nx-workspace-actions button:hover,.nx-preset-grid button:hover{background:var(--panel2);border-color:var(--line2)}.nx-preset-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.nx-preset-grid button{text-align:left;display:grid;gap:2px}.nx-preset-grid strong{font-size:12px}.nx-preset-grid span{font-size:10px;color:var(--muted)}@media(max-width:620px){.nx-preset-grid{grid-template-columns:1fr}.nx-stat-grid{grid-template-columns:repeat(3,1fr)}.nx-workspace-btn span{display:none}}`;document.head.append(s)}
function nxButton(){const bar=q('.topbar');if(!bar||bar.querySelector('[data-nx-workspace]'))return;const cloud=bar.querySelector('[data-nx-cloud]'),route=bar.querySelector('.route-pill'),btn=document.createElement('button');btn.className='nx-workspace-btn';btn.dataset.nxWorkspace='1';btn.innerHTML='◇ <span>Workspace</span>';btn.onclick=openNxWorkspace;if(cloud)cloud.after(btn);else if(route)route.before(btn);else bar.append(btn)}
nxStyles();nxButton();const nxObserver=new MutationObserver(nxButton);nxObserver.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('beforeunload',()=>nxObserver.disconnect());
