const HORDE='https://aihorde.net/api/v2';
const ANON='0000000000';
const CLIENT='NexalAI:1.1:mbusoP01';
const preferred=[[/skyfall/i,120,'Skyfall'],[/cydonia/i,112,'Cydonia'],[/behemoth/i,106,'Behemoth'],[/drummer/i,85,'TheDrummer'],[/magnum|mag-mell/i,68,'Magnum'],[/heretic|abliterat|uncensor|derestrict/i,62,'Low-refusal'],[/llama.?3|qwen|mistral|gemma/i,20,'General']];
function json(res,status,data){res.status(status).json(data)}
function headers(key){return {'Content-Type':'application/json','Client-Agent':CLIENT,'apikey':key||ANON}}
async function hf(path,opts={},timeout=12000){const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(HORDE+path,{...opts,signal:ctl.signal,headers:{'Client-Agent':CLIENT,...(opts.headers||{})}});const txt=await r.text();let d={};try{d=txt?JSON.parse(txt):{}}catch{d={raw:txt}}if(!r.ok){const e=new Error(d?.message||d?.error||`AI Horde returned ${r.status}`);e.status=r.status;e.data=d;throw e}return d}finally{clearTimeout(t)}}
async function live(){const x=await hf('/status/models?type=text');return Array.isArray(x)?x:[]}
function score(m){const name=String(m?.name||''),workers=Number(m?.count??m?.workers??0),queued=Number(m?.queued??0),jobs=Number(m?.jobs??0),eta=Number(m?.eta??9999),performance=Number(m?.performance??0);let s=workers*22+Math.min(performance,100)*1.8-Math.min(eta,600)*.65-jobs*2-queued/1000,family='Community';for(const [re,b,label] of preferred){if(re.test(name)){s+=b;family=label;break}}if(workers<1)s-=1000;return {...m,score:s,family,workers,queued,jobs,eta,performance}}
function ranked(models){return models.map(score).filter(m=>m.workers>0).sort((a,b)=>b.score-a.score)}
function modelBillions(name=''){const vals=[...String(name).matchAll(/(\d+(?:\.\d+)?)\s*[bB](?![A-Za-z])/g)].map(x=>Number(x[1])).filter(Number.isFinite);return vals.length?Math.max(...vals):0}
function capable(m){const n=String(m?.name||'');return modelBillions(n)>=8||/skyfall|cydonia|behemoth|magnum|rocinante|stheno|angelic|gemma-4-31b/i.test(n)}
function candidateModels(models,want='auto',mode='balanced'){const r=ranked(models);if(!r.length)throw new Error('No AI Horde text workers are online right now.');if(want&&want!=='auto'){const exact=r.find(m=>m.name===want);if(exact)return [exact]}const quality=r.filter(capable);const pool=quality.length?quality:r;if(mode==='fast')return [...pool].sort((a,b)=>(a.eta-b.eta)||(b.performance-a.performance)||(b.workers-a.workers)).slice(0,4);if(mode==='large')return [...pool].sort((a,b)=>(modelBillions(b.name)-modelBillions(a.name))||(b.score-a.score)).slice(0,3);if(mode==='low-refusal'){const low=pool.filter(m=>/skyfall|cydonia|drummer|heretic|abliterat|uncensor|derestrict|magnum/i.test(m.name));return (low.length?low:pool).slice(0,4)}return pool.slice(0,4)}
function prompt(messages=[],sys=''){const p=[];if(String(sys).trim())p.push(`### System:\n${String(sys).trim()}`);for(const m of (Array.isArray(messages)?messages.slice(-30):[])){const role=m?.role==='assistant'?'Assistant':m?.role==='system'?'System':'User';const c=String(m?.content||'').trim();if(c)p.push(`### ${role}:\n${c}`)}p.push('### Assistant:\n');return p.join('\n\n')}
async function modelsOp(res){const r=ranked(await live());res.setHeader('Cache-Control','s-maxage=15, stale-while-revalidate=30');json(res,200,{updatedAt:new Date().toISOString(),total:r.length,models:r.slice(0,40).map(m=>({name:m.name,family:m.family,workers:m.workers,queued:m.queued,jobs:m.jobs,eta:m.eta,performance:m.performance,score:Math.round(m.score)}))})}
async function healthOp(res){const [ms,h,p]=await Promise.all([live(),hf('/status/heartbeat').catch(()=>({ok:false})),hf('/status/performance').catch(()=>({}))]);const r=ranked(ms);json(res,200,{ok:r.length>0,activeTextModels:r.length,bestModel:r[0]?.name||null,horde:{heartbeat:h,performance:p},checkedAt:new Date().toISOString()})}
async function chatOp(req,res){let b=req.body||{};if(typeof b==='string')try{b=JSON.parse(b)}catch{}if(!Array.isArray(b.messages)||!b.messages.some(m=>m?.role==='user'&&String(m?.content||'').trim()))return json(res,400,{error:'At least one user message is required.'});if(JSON.stringify(b.messages).length>32000)return json(res,413,{error:'Conversation is too large for the free endpoint. Start a new chat.'});const candidates=candidateModels(await live(),b.model||'auto',b.mode||'balanced');const chosen=candidates[0];const payload={prompt:prompt(b.messages,b.systemPrompt||'Be useful, accurate and direct. Clearly distinguish facts from uncertainty.'),params:{n:1,max_length:Math.max(32,Math.min(Number(b.maxTokens)||500,1200)),max_context_length:4096,temperature:Math.max(.05,Math.min(Number(b.temperature)||.75,1.5)),top_p:.92,top_k:0,rep_pen:1.08,rep_pen_range:1024,frmtadsnsp:false,frmtrmblln:false,frmtrmspch:false,frmttriminc:false},models:candidates.map(x=>x.name),trusted_workers:false,slow_workers:true};const d=await hf('/generate/text/async',{method:'POST',headers:headers(b.hordeApiKey),body:JSON.stringify(payload)},15000);if(!d?.id)throw new Error(d?.message||'AI Horde did not return a generation ID.');json(res,202,{jobId:d.id,model:chosen,candidateModels:candidates.map(x=>x.name),warnings:d.warnings||[]})}
async function jobOp(req,res){const id=String(req.query?.id||'').trim();if(!id)return json(res,400,{error:'Missing job id.'});if(req.method==='DELETE'){const d=await hf('/generate/text/status/'+encodeURIComponent(id),{method:'DELETE'});return json(res,200,{cancelled:true,data:d})}if(req.method!=='GET')return json(res,405,{error:'Method not allowed'});const d=await hf('/generate/text/status/'+encodeURIComponent(id));const g=Array.isArray(d.generations)?d.generations[0]:null;json(res,200,{done:Boolean(d.done),faulted:Boolean(d.faulted),waitTime:d.wait_time??null,queuePosition:d.queue_position??null,waiting:d.waiting??null,processing:d.processing??null,finished:d.finished??null,kudos:d.kudos??null,response:g?.text||null,model:g?.model||null,worker:g?.worker_name||null,rawState:g?.state||null})}
module.exports=async function(req,res){const op=String(req.query?.op||'health');try{if(op==='models'&&req.method==='GET')return await modelsOp(res);if(op==='health'&&req.method==='GET')return await healthOp(res);if(op==='chat'&&req.method==='POST')return await chatOp(req,res);if(op==='job')return await jobOp(req,res);return json(res,404,{error:'Unknown operation'})}catch(e){const status=Number(e.status)>=400&&Number(e.status)<500?Number(e.status):502;return json(res,status,{error:e.message||'Upstream request failed',details:e.data||undefined})}}
